# Jenkins inbound agent (Alpine + JDK17)
FROM --platform=linux/amd64 jenkins/inbound-agent:latest-alpine-jdk17

USER root
ARG TF_VERSION=1.12.2

# System tools + Terraform v1.12.2
RUN apk add --no-cache \
      py3-pip python3 curl jq openssl aws-cli unzip git py3-requests \
      busybox-extras netcat-openbsd \
 && curl -fsSL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_SHA256SUMS -o /tmp/terraform_SHA256SUMS \
 && curl -fsSL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o /tmp/terraform_${TF_VERSION}_linux_amd64.zip \
 && (cd /tmp && grep "terraform_${TF_VERSION}_linux_amd64.zip" terraform_SHA256SUMS | sha256sum -c -) \
 && unzip /tmp/terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin \
 && rm -f /tmp/terraform_${TF_VERSION}_linux_amd64.zip /tmp/terraform_SHA256SUMS

# Python venv
RUN python3 -m venv /opt/venv \
 && . /opt/venv/bin/activate \
 && pip install --upgrade pip requests \
 && deactivate
ENV PATH="/opt/venv/bin:$PATH"

# Entrypoint
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

USER jenkins
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

